name: Build and publish execution client

on:
  workflow_dispatch:
    inputs:
      client:
        description: "Execution client to build with native ERC-4337 tracers"
        required: true
        type: choice
        options:
          - go-ethereum
          - nitro

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup client directory
        run: ./build_scripts/${{inputs.client}}.sh --only-setup

      - name: Get client version
        run: |
          cd ./${{inputs.client}} && \
          git fetch --tags && \
          echo "CLIENT_GIT_TAG=$(git describe --tags)" >> $GITHUB_ENV && \
          cd ..

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{inputs.client}}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: stackupwallet/${{inputs.client}}:${{env.CLIENT_GIT_TAG}}
